Grand.Web/Areas/Admin/Controllers/GiftCardController.cs
using Grand.Core;
using Grand.Framework.Controllers;
using Grand.Framework.Kendoui;
using Grand.Framework.Mvc.Filters;
using Grand.Framework.Security.Authorization;
using Grand.Services.Localization;
using Grand.Services.Orders;
using Grand.Services.Security;
using Grand.Web.Areas.Admin.Interfaces;
using Grand.Web.Areas.Admin.Models.Orders;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Grand.Web.Areas.Admin.Controllers
{
    [PermissionAuthorize(PermissionSystemName.GiftCards)]
    public partial class GiftCardController : BaseAdminController
    {
        #region Fields
        private readonly IGiftCardViewModelService _giftCardViewModelService;
        private readonly IGiftCardService _giftCardService;
        private readonly ILocalizationService _localizationService;
        #endregion

        #region Constructors

        public GiftCardController(
            IGiftCardViewModelService giftCardViewModelService,
            IGiftCardService giftCardService,
            ILocalizationService localizationService)
        {
            _giftCardViewModelService = giftCardViewModelService;
            _giftCardService = giftCardService;
            _localizationService = localizationService;
        }

        #endregion

        #region Methods

        //list
        public IActionResult Index() => RedirectToAction("List");

        public IActionResult List()
        {
            var model = _giftCardViewModelService.PrepareGiftCardListModel();
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.List)]
        [HttpPost]
        public async Task<IActionResult> GiftCardList(DataSourceRequest command, GiftCardListModel model)
        {
            var (giftCardModels, totalCount) = await _giftCardViewModelService.PrepareGiftCardModel(model, command.Page, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = giftCardModels.ToList(),
                Total = totalCount
            };

            return Json(gridModel);
        }

        [PermissionAuthorizeAction(PermissionActionName.Create)]
        public async Task<IActionResult> Create()
        {
            var model = await _giftCardViewModelService.PrepareGiftCardModel();
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        public async Task<IActionResult> Create(GiftCardModel model, bool continueEditing)
        {
            if (ModelState.IsValid)
            {
                var giftCard = await _giftCardViewModelService.InsertGiftCardModel(model);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Added"));
                return continueEditing ? RedirectToAction("Edit", new { id = giftCard.Id }) : RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            model = await _giftCardViewModelService.PrepareGiftCardModel(model);
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Preview)]
        public async Task<IActionResult> Edit(string id)
        {
            var giftCard = await _giftCardService.GetGiftCardById(id);
            if (giftCard == null)
                //No gift card found with the specified id
                return RedirectToAction("List");

            var model = await _giftCardViewModelService.PrepareGiftCardModel(giftCard);
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public async Task<IActionResult> Edit(GiftCardModel model, bool continueEditing)
        {
            var giftCard = await _giftCardService.GetGiftCardById(model.Id);
            if (giftCard == null)
                return RedirectToAction("List");

            await _giftCardViewModelService.FillGiftCardModel(giftCard, model);

            if (ModelState.IsValid)
            {
                giftCard = await _giftCardViewModelService.UpdateGiftCardModel(giftCard, model);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Updated"));

                if (continueEditing)
                {
                    //selected tab
                    await SaveSelectedTabIndex();

                    return RedirectToAction("Edit", new { id = giftCard.Id });
                }
                return RedirectToAction("List");
            }

            //If we got this far, something failed, redisplay form
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost]
        public IActionResult GenerateCouponCode()
        {
            return Json(new { CouponCode = _giftCardService.GenerateGiftCardCode() });
        }

        [PermissionAuthorizeAction(PermissionActionName.Edit)]
        [HttpPost, ActionName("Edit")]
        [FormValueRequired("notifyRecipient")]
        public async Task<IActionResult> NotifyRecipient(GiftCardModel model)
        {
            var giftCard = await _giftCardService.GetGiftCardById(model.Id);

            if (!CommonHelper.IsValidEmail(giftCard.RecipientEmail))
                ModelState.AddModelError("", "Recipient email is not valid");
            if (!CommonHelper.IsValidEmail(giftCard.SenderEmail))
                ModelState.AddModelError("", "Sender email is not valid");

            try
            {
                if (ModelState.IsValid)
                {
                    await _giftCardViewModelService.NotifyRecipient(giftCard, model);
                }
                else
                    ErrorNotification(ModelState);
            }
            catch (Exception exc)
            {
                ErrorNotification(exc, false);
            }
            model = await _giftCardViewModelService.PrepareGiftCardModel(giftCard);
            return View(model);
        }

        [PermissionAuthorizeAction(PermissionActionName.Delete)]
        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var giftCard = await _giftCardService.GetGiftCardById(id);
            if (giftCard == null)
                //No gift card found with the specified id
                return RedirectToAction("List");

            if (giftCard.GiftCardUsageHistory.Any())
                ModelState.AddModelError("", _localizationService.GetResource("Admin.GiftCards.PreventDeleted"));

            if (ModelState.IsValid)
            {
                await _giftCardViewModelService.DeleteGiftCard(giftCard);
                SuccessNotification(_localizationService.GetResource("Admin.GiftCards.Deleted"));
                return RedirectToAction("List");
            }
            ErrorNotification(ModelState);
            return RedirectToAction("Edit", new { id = giftCard.Id });
        }

        //Gif card usage history

        [PermissionAuthorizeAction(PermissionActionName.Preview)]
        [HttpPost]
        public async Task<IActionResult> UsageHistoryList(string giftCardId, DataSourceRequest command)
        {
            var giftCard = await _giftCardService.GetGiftCardById(giftCardId);
            if (giftCard == null)
                throw new ArgumentException("No gift card found with the specified id");

            var (giftCardUsageHistoryModels, totalCount) = await _giftCardViewModelService.PrepareGiftCardUsageHistoryModels(giftCard, command.Page, command.PageSize);
            var gridModel = new DataSourceResult
            {
                Data = giftCardUsageHistoryModels.ToList(),
                Total = totalCount
            };

            return Json(gridModel);
        }

        #endregion
    }
}

Grand.Web/Areas/Admin/Views/GiftCard/Create.cshtml
@model GiftCardModel
@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.AddNew").Text;
}
<form asp-area="@Constants.AreaAdmin" asp-controller="GiftCard" asp-action="Create" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>
                        @T("Admin.GiftCards.AddNew")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.GiftCards.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions btn-group btn-group-devided">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        <vc:admin-widget widget-zone="gift_card_details_buttons" additional-data="null" />
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>

Grand.Web/Areas/Admin/Views/GiftCard/Edit.cshtml
@model GiftCardModel
@{
    //page title
    ViewBag.Title = T("Admin.GiftCards.EditGiftCardDetails").Text;
}
<form asp-area="@Constants.AreaAdmin" asp-controller="GiftCard" asp-action="Edit" method="post">
    
    <div class="row">
        <div class="col-md-12">
            <div class="x_panel light form-fit">
                <div class="x_title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>
                        @T("Admin.GiftCards.EditGiftCardDetails")
                        <small><i class="fa fa-arrow-circle-left"></i>@Html.ActionLink(T("Admin.GiftCards.BackToList").Text, "List")</small>
                    </div>
                    <div class="actions btn-group btn-group-devided">
                        <button class="btn btn-success" type="submit" name="save"><i class="fa fa-check"></i> @T("Admin.Common.Save") </button>
                        <button class="btn btn-success" type="submit" name="save-continue"><i class="fa fa-check-circle"></i> @T("Admin.Common.SaveContinue") </button>
                        <span id="giftcard-delete" class="btn red"><i class="fa fa-trash-o"></i> @T("Admin.Common.Delete")</span>
                        <vc:admin-widget widget-zone="gift_card_details_buttons" additional-data="null" />
                    </div>
                </div>
                <div class="x_content form">
                   <partial name="_CreateOrUpdate" model="Model" />
                </div>
            </div>
        </div>
    </div>
</form>
<admin-delete-confirmation button-id="giftcard-delete"/>

Grand.Web/Areas/Admin/Views/GiftCard/List.cshtml
@model GiftCardListModel
@inject AdminAreaSettings adminAreaSettings

@{
    //page title
    ViewBag.Title = T("Admin.GiftCards").Text;
}

<div class="row">
    <div class="col-md-12">
        <div class="x_panel light form-fit">
            <div class="x_title">
                <div class="caption">
                    <i class="fa fa-gift"></i>
                    @T("Admin.GiftCards")
                </div>
                <div class="actions btn-group btn-group-devided">
                    <a href="@Url.Action("Create")" class="btn green"><i class="fa fa-plus"></i><span class="d-none d-sm-inline"> @T("Admin.Common.AddNew") </span></a>
                    <vc:admin-widget widget-zone="gift_card_list_buttons" additional-data="null" />
                </div>
            </div>
            <div class="x_content form">
                <div class="form-horizontal">
                    <div class="form-body">
                        <div class="form-group">
                            <admin-label asp-for="ActivatedId" />
                            <div class="col-md-9 col-sm-9">
                                <admin-select asp-for="ActivatedId" asp-items="Model.ActivatedList" />
                            </div>
                        </div>
                        <div class="form-group">
                            <admin-label asp-for="CouponCode" />
                            <div class="col-md-9 col-sm-9">
                                <admin-input asp-for="CouponCode" />
                            </div>
                        </div>
                        <div class="form-group">
                            <admin-label asp-for="RecipientName" />
                            <div class="col-md-9 col-sm-9">
                                <admin-input asp-for="RecipientName" />
                            </div>
                        </div>
                    </div>
                    <div class="form-actions">
                        <div class="row">
                            <div class="offset-md-3 offset-sm-3 col-md-9 col-sm-9">
                                <button class="btn btn-success filter-submit" id="search-giftcards">
                                    <i class="fa fa-search"></i> @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="x_content">
                <div id="giftcards-grid"></div>
            </div>
        </div>
    </div>
</div>

<script>
        $(document).ready(function () {
            $("#giftcards-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("GiftCardList", "GiftCard"))",
                            type: "POST",
                            dataType: "json",
                            data: additionalData
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "AmountStr",
                    title: "@T("Admin.GiftCards.Fields.Amount")",
                    template: '<a class="k-link" href="Edit/#=Id#">#=AmountStr#</a>',
                    width: 100,
                }, {
                    field: "RemainingAmountStr",
                    title: "@T("Admin.GiftCards.Fields.RemainingAmount")",
                    template: '<a class="k-link" href="Edit/#=Id#">#=RemainingAmountStr#</a>',
                    width: 100,
                }, {
                    field: "GiftCardCouponCode",
                    title: "@T("Admin.GiftCards.Fields.GiftCardCouponCode")",
                    template: '<a class="k-link" href="Edit/#=Id#">#=GiftCardCouponCode#</a>',
                    width: 120,
                }, {
                    field: "RecipientName",
                    title: "@T("Admin.GiftCards.Fields.RecipientName")",
                    minScreenWidth: 750,
                    width: 150,
                }, {
                    field: "IsGiftCardActivated",
                    title: "@T("Admin.GiftCards.Fields.IsGiftCardActivated")",
                    width: 100,
                    headerAttributes: { style: "text-align:center" },
                    attributes: { style: "text-align:center" },
                    template: '# if(IsGiftCardActivated) {# <i class="fa fa-check" aria-hidden="true" style="color:green"></i> #} else {# <i class="fa fa-times" aria-hidden="true" style="color:red"></i> #} #'
                }, {
                    field: "CreatedOn",
                    title: "@T("Admin.GiftCards.Fields.CreatedOn")",
                    width: 180,
                    type: "date",
                    format: "{0:G}"
                }]
            });
        });
</script>
<script>

        $(document).ready(function () {

            $('#search-giftcards').click(function () {
                var grid = $('#giftcards-grid').data('kendoGrid');
                grid.dataSource.page(1); //new search. Set page size to 1
                //grid.dataSource.read(); we already loaded the grid above using "page" function
                return false;
            });
        });

        $("#@Html.FieldIdFor(model => model.CouponCode)").keydown(function (event) {
            if (event.keyCode == 13) {
                $("#search-giftcards").click();
                return false;
            }
        });

        function additionalData() {
            var data = {
                ActivatedId: $('#@Html.FieldIdFor(model => model.ActivatedId)').val(),
                CouponCode: $('#@Html.FieldIdFor(model => model.CouponCode)').val(),
                RecipientName: $('#@Html.FieldIdFor(model => model.RecipientName)').val()
            };
            addAntiForgeryToken(data);
            return data;
        }

</script>

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.TabHistory.cshtml
@model GiftCardModel
@inject AdminAreaSettings adminAreaSettings
@{
    <vc:admin-widget widget-zone="gift_card_details_history_top" additional-data="Model" />
    <div id="usagehistory-grid"></div>
    <vc:admin-widget widget-zone="gift_card_details_history_bottom" additional-data="Model" />
    <script>
        $(document).ready(function () {
            $("#usagehistory-grid").kendoGrid({
                dataSource: {
                    transport: {
                        read: {
                            url: "@Html.Raw(Url.Action("UsageHistoryList", "GiftCard", new { giftCardId = Model.Id }))",
                            type: "POST",
                            dataType: "json",
                            data: addAntiForgeryToken
                        }
                    },
                    schema: {
                        data: "Data",
                        total: "Total",
                        errors: "Errors"
                    },
                    error: function(e) {
                        display_kendoui_grid_error(e);
                        // Cancel the changes
                        this.cancelChanges();
                    },
                    pageSize: @(adminAreaSettings.DefaultGridPageSize),
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                pageable: {
                    refresh: true,
                    pageSizes: [@(adminAreaSettings.GridPageSizes)]
                },
                editable: {
                    confirmation: false,
                    mode: "inline"
                },
                scrollable: false,
                columns: [{
                    field: "CreatedOn",
                    title: "@T("Admin.GiftCards.History.CreatedOn")",
                    width: 200,
                    type: "date",
                    format: "{0:G}"
                }, {
                    field: "OrderId",
                    title: "@T("Admin.GiftCards.History.Order")",
                    width: 200,
                        template: '<a href="@Url.Action("Edit", "Order")/#=OrderId#" class="k-button"><span class="k-icon k-i-eye"></span>&nbsp;@T("Admin.Common.View") #=OrderNumber#</a>'
                }, {
                    field: "UsedValue",
                    title: "@T("Admin.GiftCards.History.UsedValue")",
                    width: 200
                }]
            });
        });
    </script>
}

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.TabInfo.cshtml
@model GiftCardModel
<script>
    $(document).ready(function () {
        $("#@Html.FieldIdFor(model => model.GiftCardTypeId)").change(toggleGiftCardType);
        toggleGiftCardType();
    });

    function toggleGiftCardType() {
        var selectedGiftCardTypeId = $("#@Html.FieldIdFor(model => model.GiftCardTypeId)").val();
        if (selectedGiftCardTypeId == @(((int)GiftCardType.Virtual).ToString())) {
            $('#pnlRecipientEmail').show();
            $('#pnlSenderEmail').show();
            $('#pnlNotifyRecipient').show();
        }
        else {
            $('#pnlRecipientEmail').hide();
            $('#pnlSenderEmail').hide();
            $('#pnlNotifyRecipient').hide();
        }
    }
</script>
<div class="form-horizontal">
    <vc:admin-widget widget-zone="gift_card_details_info_top" additional-data="Model" />
    <div class="form-body">
        <div class="form-group">
            <admin-label asp-for="GiftCardTypeId" />
            <div class="col-md-9 col-sm-9">
                <admin-select asp-for="GiftCardTypeId" asp-items="((GiftCardType)Model.GiftCardTypeId).ToSelectList(Context)" />
                <span asp-validation-for="GiftCardTypeId"></span>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.PurchasedWithOrderId))
        {
            <div class="form-group">
                <admin-label asp-for="PurchasedWithOrderId" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label"><a href="@Url.Action("Edit", "Order", new { Id = Model.PurchasedWithOrderId })" class="k-button"><span class="k-icon k-i-eye"></span>&nbsp;@T("Admin.Common.View") #@Model.PurchasedWithOrderNumber</a></label>
                </div>
            </div>
        }
        <div class="form-group">
            <admin-label asp-for="Amount" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="Amount" />
                @if (!String.IsNullOrEmpty(Model.Id))
                {
                    <text>[@Model.CurrencyCode]</text>
                }
                <span asp-validation-for="Amount"></span>
            </div>
        </div>
        @if (String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group">
                <admin-label asp-for="CurrencyCode" class="col-sm-3 control-label" />
                <div class="col-md-9 col-sm-9">
                    <admin-select asp-for="CurrencyCode" asp-items="Model.AvailableCurrencies" />
                    <span asp-validation-for="CurrencyCode"></span>
                </div>
            </div>
        }
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group">
                <admin-label asp-for="RemainingAmountStr" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label">@Model.RemainingAmountStr</label>
                </div>
            </div>
        }
        <div class="form-group">
            <admin-label asp-for="IsGiftCardActivated" />
            <div class="col-md-9 col-sm-9">
                <label class="mt-checkbox mt-checkbox-outline control control-checkbox">
                    <admin-input asp-for="IsGiftCardActivated" />
                    <div class="control__indicator"></div>
                </label>
                <span asp-validation-for="IsGiftCardActivated"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="GiftCardCouponCode" />
            <div class="col-md-4 col-sm-6">
                <div class="input-group">
                    <div class="input-group-control">
                        <admin-input asp-for="GiftCardCouponCode" />
                    </div>
                    <div class="input-group-append">
                        <input type="button" id="generateCouponCode" class="btn default" value="@T("Admin.GiftCards.Fields.GiftCardCouponCode.Generate")" />
                    </div>
                </div>
                <span asp-validation-for="GiftCardCouponCode"></span>
                <script>
                        $(document).ready(function () {
                            $('#generateCouponCode').click(function () {

                                var postData = {
                                };
                                addAntiForgeryToken(postData);

                                $.ajax({
                                    cache:false,
                                    type: "POST",
                                    url: "@(Url.Action("GenerateCouponCode", "GiftCard"))",
                                    data: postData,
                                    success: function (data) {
                                        $('#@Html.FieldIdFor(model => model.GiftCardCouponCode)').val(data.CouponCode);
                                    },
                                    error:function (xhr, ajaxOptions, thrownError){
                                        alert('Failed to generate code.');
                                    }
                                });
                            });
                        });
                </script>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="RecipientName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="RecipientName" />
                <span asp-validation-for="RecipientName"></span>
            </div>
        </div>
        <div class="form-group" id="pnlRecipientEmail">
            <admin-label asp-for="RecipientEmail" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="RecipientEmail" />
                <span asp-validation-for="RecipientEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="SenderName" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SenderName" />
                <span asp-validation-for="SenderName"></span>
            </div>
        </div>
        <div class="form-group" id="pnlSenderEmail">
            <admin-label asp-for="SenderEmail" />
            <div class="col-md-9 col-sm-9">
                <admin-input asp-for="SenderEmail" />
                <span asp-validation-for="SenderEmail"></span>
            </div>
        </div>
        <div class="form-group">
            <admin-label asp-for="Message" />
            <div class="col-md-9 col-sm-9">
                <admin-textarea asp-for="Message"></admin-textarea>
                <span asp-validation-for="Message"></span>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group" id="pnlNotifyRecipient">
                <admin-label asp-for="IsRecipientNotified" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label">@Model.IsRecipientNotified.ToString()</label>
                    <button type="submit" name="notifyRecipient" class="k-button"><span class="k-icon k-i-notification"></span>&nbsp;@T("Admin.GiftCards.Fields.IsRecipientNotified.Notify")</button>
                </div>
            </div>
        }
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <div class="form-group">
                <admin-label asp-for="CreatedOn" />
                <div class="col-md-9 col-sm-9">
                    <label class="control-label"> @Model.CreatedOn</label>
                </div>
            </div>
        }
    </div>
    <vc:admin-widget widget-zone="gift_card_details_info_bottom" additional-data="Model" />
</div>

Grand.Web/Areas/Admin/Views/GiftCard/_CreateOrUpdate.cshtml
@model GiftCardModel

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />
<admin-tabstrip name="giftcard-edit">
    <items>
        <tabstrip-item text="@T("Admin.GiftCards.Info")" tab-index="0">
            <content>
                <div>
                    <partial name="_CreateOrUpdate.TabInfo" model="Model" />
                </div>
            </content>
        </tabstrip-item>
        @if (!String.IsNullOrEmpty(Model.Id))
        {
            <tabstrip-item text="@T("Admin.GiftCards.History")" tab-index="1">
                <content>
                    <div>
                        <partial name="_CreateOrUpdate.TabHistory" model="Model" />
                    </div>
                </content>
            </tabstrip-item>
        }
        <vc:admin-widget widget-zone="giftcard_details_tabs" additional-data="Model" />
    </items>
</admin-tabstrip>